name: roj_gaar_app
description: "Rojgaar"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil:
  get:
  dio:
  hive:
  flutter_secure_storage:
  flutter_html:
  flutter_svg:
  firebase_core:
  fluttertoast:
  image_picker:
  file_picker:
  open_file_plus:
  url_launcher:
  flutter_exif_rotation:
  photo_view:
  chewie: ^1.5.0
  cached_network_image:
  intl:
  http:
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
